sudo: required
language: generic
services:
    - docker

before_install:
    - docker build -t thomasdavis083/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true thomasdavis083/react-test npm test

after_success:
    - docker build -t thomasdavis083/multi-client ./client
    - docker build -t thomasdavis083/multi-nginx ./nginx
    - docker build -t thomasdavis083/multi-server ./server
    - docker build -t thomasdavis083/multi-worker ./worker
    # log in to docker hub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push thomasdavis083/multi-client
    - docker push thomasdavis083/multi-worker
    - docker push thomasdavis083/multi-server
    - docker push thomasdavis083/multi-nginx